controller_manager:
  ros__parameters:
    update_rate: 2 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity